run-dist:
	./build/install/app/bin/app

run:
	./gradlew run

install-dist:
	make clean
	./gradlew installDist

clean:
	./gradlew clean

lint:
	./gradlew spotlessCheck

lint-fix:
	./gradlew spotlessApply